//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVEVuln.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CVE_VulnEntities : DbContext
    {
        public CVE_VulnEntities()
            : base("name=CVE_VulnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Vulnerabilities> Vulnerabilities { get; set; }
        public virtual DbSet<AccountInRoles> AccountInRoles { get; set; }
    }
}
