//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVEVuln.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    public partial class Vulnerabilities : Resource
    {
        public int Id { get; set; }
        [JsonProperty("cve_id")]
        public string cve_id { get; set; }
        [JsonProperty("cwe_id")]
        public string cwe_id { get; set; }
        [JsonProperty("summary")]
        public string summary { get; set; }
        [JsonProperty("cvss_score")]
        public string cvss_score { get; set; }
        [JsonProperty("exploit_count")]
        public string exploit_count { get; set; }
        [JsonProperty("publish_date")]
        public Nullable<System.DateTime> publish_date { get; set; }
        [JsonProperty("update_date")]
        public Nullable<System.DateTime> update_date { get; set; }
        [JsonProperty("url")]
        public string url { get; set; }
    }
}
